#include <imgui-cocos.hpp>
#include <Geode/modify/MenuLayer.hpp>
#include <iostream>
#include "bools.h"
#include <geode.custom-keybinds/include/Keybinds.hpp>
#include <Geode/modify/CCScheduler.hpp>
#include <Geode/modify/FMODAudioEngine.hpp>
#include <Geode/modify/PlayLayer.hpp>
#include <Geode/modify/CCDrawNode.hpp>
#include <Geode/modify/LevelInfoLayer.hpp>
#include <Geode/modify/ShaderLayer.hpp>
#include <Geode/modify/EditorPauseLayer.hpp>
#include <Geode/modify/EditorUI.hpp>
#include <Geode/modify/LevelTools.hpp>
#include <Geode/modify/PauseLayer.hpp>
#include <Geode/modify/EditLevelLayer.hpp>
#include <Geode/modify/SliderTouchLogic.hpp>
#include <Geode/modify/LevelEditorLayer.hpp>
#include <Geode/modify/GameManager.hpp>
#include <Geode/modify/GameStatsManager.hpp>